name: Publish Docker image

on:
  push:
    branches:
    - main

  # release:
  #   types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    # permissions:
    #   packages: write
    #   contents: read
    #   attestations: write
    #   id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
